### ISSUE TITLE
Two same widget area issue 

### ISSUE THREAD

**Issue by reardestani** [philipnewcomer/widget-output-filters#1]
When two same widget area (e.g. single post widget area) are added in a page via widget area shortcode (a shortcode to add widget to a page), the below notice appears and none of the widgets appear.

Notice: Undefined property: Widget_Output_Filters::$id_base in ...

Is there any solution?

**Comment by philipnewcomer** [comment]
What is the plugin you are using to embed the widget areas in the page? I will give it a try and see if I can reproduce the issue.

**Comment by reardestani** [comment]
I am using Visual Composer. Both of the **Widgetised Sidebar** must be set to same widget area.

<img width="632" alt="screenshot at sep 09 07-28-03" src="https://cloud.githubusercontent.com/assets/2968507/18374089/0262303a-765f-11e6-8322-ce63fd10f512.png">

**Comment by philipnewcomer** [comment]
Visual Composer is a premium plugin, so I can't test this unless someone provides me with a copy of it. If you'd like to send me your copy so I can test this, send it as an email attachment (or a link to a downloadable ZIP file) to contact (at) philipnewcomer.net and I'll take a look.

**Comment by reardestani** [comment]
Please check your email.

**Comment by philipnewcomer** [comment]
I have released an update to the codebase which addresses this issue (see 5ce38b41df7b18be4a9120546170f8901bae8c35 for the diff if you want to apply it manually). Please ask your theme vendor to update the theme with the new version of the library.
